### ISSUE TITLE
fanart.tv plugin broken

### ISSUE THREAD

**Issue by salim-b** [musicbrainz/picard-plugins#120]
Hi, since some update of Picard the fanart.tv. plugin doesn't work anymore. Although it appears in the settings, is activated, correctly set up with my API key etc, no cover images get downloaded.

I'm using Picard v1.4.2 and fanart.tv plugin v0.5 on Ubuntu 16.04 LTS. Picard is installed from the [official repository](https://launchpad.net/~musicbrainz-developers/+archive/ubuntu/stable).

**Comment by phw** [comment]
The plugin still works for me, but I did only test the Picard 2.0 version. I would currently recommend to use the Picard 2.0 beta anyway, see https://blog.musicbrainz.org/2018/03/19/picard-2-0-beta2-announcement/

@salim-b  If this still doesn't work for you please have a look at Help > View Error/Debug Log if there are any error messages there and post the output.

**Comment by salim-b** [comment]
@phw Ok, thanks for the hint to use v2.0 beta. But where can I get a binary release of it suited for Ubuntu 16.04? On the [GitHub releases page](https://github.com/metabrainz/picard/releases) there are only prebuilt versions available for Windows and macOS. And in the [MusicBrainz daily PPA](https://launchpad.net/~musicbrainz-developers/+archive/ubuntu/daily?field.series_filter=xenial) there's no v2.0 release available for Ubuntu 16.04.

**Comment by phw** [comment]
Yes, the PPA version currently does not build on 16.04 since 16.04 does not provide the required libraries. At the moment the latest 2.0 daily builds are only available for Ubuntu 17.10 or later.

Having said this I don't really see a reason why the Fanart.tv plugin for Picard 1.0 should not work anymore, so maybe try again and have a look at the debug log as described above. Also double check you have entered the correct API key.

**Comment by salim-b** [comment]
In the error/debug log there's the following line after startup:
```
I: 14:20:23 Plugin directory '/usr/lib/picard/contrib/plugins' doesn't exist
```

...while the plugins actually are in `~/.config/MusicBrainz/Picard/plugins`. In the `Picard.conf` I can't find anything to set the plugin dir...

**Comment by phw** [comment]
I am closing this since it is working for me and this bug report does not provide enough information to see the issue.

Please try with Picard 2.0 if possible. And feel free to let me know if this issue still exists and I will reopen the issue

**Comment by ghost** [comment]
I'm getting something like this in the log:

```
D: 03:04:11,441 coverart.providers.cover_art_providers:82: CA Providers order: Local > Cover Art Archive > Amazon > Whitelist > CaaReleaseGroup > fanart.tv
D: 03:04:11,442 coverart.providers.enabled:130: Local disabled by user
D: 03:04:11,443 coverart.next_in_queue:144: Skipping cover art provider Local ...
D: 03:04:11,443 coverart.providers.enabled:130: Cover Art Archive disabled by user
D: 03:04:11,444 coverart.next_in_queue:144: Skipping cover art provider Cover Art Archive ...
D: 03:04:11,445 coverart.providers.enabled:130: Amazon disabled by user
D: 03:04:11,445 coverart.next_in_queue:144: Skipping cover art provider Amazon ...
D: 03:04:11,446 coverart.providers.enabled:130: Whitelist disabled by user
D: 03:04:11,446 coverart.next_in_queue:144: Skipping cover art provider Whitelist ...
D: 03:04:11,447 coverart.providers.enabled:130: CaaReleaseGroup disabled by user
D: 03:04:11,447 coverart.next_in_queue:144: Skipping cover art provider CaaReleaseGroup ...
D: 03:04:11,448 coverart.providers.enabled:130: fanart.tv disabled by user
D: 03:04:11,449 coverart.next_in_queue:144: Skipping cover art provider fanart.tv ...
```

I'm on windows, with the following versions:

```
MusicBrainz Picard
Version 2.0.3
PyQt 5.10.1
Qt 5.10.1
Mutagen 1.41.0
Discid discid 1.1.1, libdiscid 0.6.2
astrcmp C
SSL OpenSSL 1.0.2o 27 Mar 2018
```

**Comment by phw** [comment]
You have to configure which cover art providers to use in Options > Cover Art.

You can choose which providers to use and in which order they are checked.

**Comment by ghost** [comment]
Thanks 👍
