### ISSUE TITLE
support mp3gain alternative

### ISSUE THREAD

**Issue by bgemmill** [musicbrainz/picard-plugins#121]
Since mp3gain was dropped from debian due to being unmaintained, from Ubuntu 16.04 onwards it's only available from unofficial sources:
https://launchpad.net/~flexiondotorg/+archive/ubuntu/audio

Of the alternatives, it looks like bs1770gain is the most recently maintained as of 2017:
http://bs1770gain.sourceforge.net/

I would have suggested rgain as well, but that also looks abandoned as of mid 2016:
https://pypi.python.org/pypi/rgain

**Comment by phw** [comment]
The new replaygain2 plugin (which will be available for download in a few hours) uses the more modern [rsgain](https://github.com/complexlogic/rsgain) utility. See #336 for details.

 The old replaygain plugin is considered deprecated and will be removed in the future.
