### ISSUE TITLE
Soundtrack plugin: "Album Artist Sort Order" not set correctly

### ISSUE THREAD

**Issue by loewenheim** [musicbrainz/picard-plugins#131]
The plugin replaces the `albumartist` tag with "Soundtrack", but not the `albumartistsort` tag, leading to an inconsistency.

**Comment by Sophist-UK** [comment]
I agree - this does lead to an inconsistency. Fix submitted in #132.

That said, the functionality of this plugin - and a fix for consistency - can be achieved using tagging scripts.

Personally I would prefer to see this plugin removed and replaced by some examples in the Picard help web pages.

**Comment by loewenheim** [comment]
Are you saying that you would prefer to see alterations of this kind done as scripts rather than plugins? Because I was thinking of making a script of a similar scope into a plugin, but now I'm reconsidering.

**Comment by Sophist-UK** [comment]
I am in two minds really.

Plugins are easier for novice users to use. But require more maintenance. 

If people want to tweak how their tagging works, they should IMO really learn about scripts. And most people want to tweak the file paths and naming and so have to learn it anyway.

**Comment by phw** [comment]
I picked this fix also for the 2.0 branch
