### ISSUE TITLE
Enabling Classical extras plugin makes the Options panel huge

### ISSUE THREAD

**Issue by tylla** [musicbrainz/picard-plugins#135]
I was redirected from the MetaBrainzTickets here so here is the issue: @MetaTunes 

The Options panel gets huge (around 1400x1000), so huge that all four sides are off the screen, no buttons, or title bar can be seen and the categories on the left side can barely be seen. (see attached pic.)
![musicbrainzpicard_options_toobig](https://user-images.githubusercontent.com/4119572/34417157-48309b6a-ebf7-11e7-9d3f-5db258aba559.png)

The steps to reproduce:

- enable the Classical Extras plugin
- save the options (Make it So!)
- reopen the Options window
- BANG it's big.

The only way to get back the normal sized Options panel is to disable the Classical Extras plugin (either deleting from the ini file, or (if lucky enough) by opening the Plugins section of the Options and disabling from there).

I tried reinstalling the program from scratch, even starting with a fresh new ini file, nothing helps. Not even setting the options_size parameter made any difference.

I would say the Classical Extras plugin's configuration panel is way too big to fit in my screen.
Maybe it should be resized to fit smaller screens.
In parallel I suggested in the other ticket that Picard should incorporate some measures to limit the size of the Options panel and maybe use scroll-bars.

I am using Picard 1.4.2 on Debian Stretch 9.3 (and on Debian Stretch 8.9) on a Lenovo X201 laptop with 1280x800 screen.

**Comment by Sophist-UK** [comment]
@MetaTunes ping.

**Comment by MetaTunes** [comment]
I am aware of the issue - at the moment a large screen is needed. I can't look at it right now, but will try and do so some time over the next week.

**Comment by Sophist-UK** [comment]
@MetaTunes : I suspect that you just need to set some maximum size constraints in the Qt UI Designer.

**Comment by MetaTunes** [comment]
Try the updated UI files at https://github.com/MetaTunes/picard-plugins/tree/1.0/plugins/classical_extras

**Comment by MetaTunes** [comment]
Some further minor improvements made. Release 0.8.8 has updated UI - see https://github.com/MetaTunes/picard-plugins/releases/tag/v0.8.8 for updated zip.

**Comment by MetaTunes** [comment]
@tylla : Can you confirm that the fix works - then this issue can be closed. Ta.

**Comment by mineo** [comment]
@MetaTunes Slightly unrelated, but do you intend to keep new versions of the plugin outside of this repository? The last 5 months of development are unfortunately not available for any user at the moment.

**Comment by MetaTunes** [comment]
@mineo - not quite sure what you mean. All the releases are available at https://github.com/MetaTunes/picard-plugins/releases
Just install classical_extras.zip
However, I would recommend using the latest release (0.8.8) - it is more stable and functional than the earlier releases.
Once I've tidied this up (and subject to any critical bugs emerging), I'll issue a pull request for it to replace the main repository version.

**Comment by MetaTunes** [comment]
@tylla  - have you checked that the latest version is OK on your Debian platform? If so, could you close this issue please?

**Comment by mineo** [comment]
@MetaTunes That's something noone will ever discover, most people will use the built-in plugin management of Picard.

**Comment by tylla** [comment]
@MetaTunes sorry, now back online. Will give it a try as soon as I get some spare time (a few days) and report back.

**Comment by MetaTunes** [comment]
@tylla - Thanks. Hopefully I can then do the next "official" release.
@mineo - You can keep abreast of Classical Extras developments and discussion at https://community.metabrainz.org/t/classical-extras-plugin/300217 - which is the best place for any general discussion as this issue will be closed shortly.

**Comment by tylla** [comment]
@MetaTunes I've tested v0.8.8 beta and it solved the problem, the Options window was normally sized and the bigger content in the plugin's options panel had scroll-bars as it should be. So if you think so you can make he release and can close this issue.

**Comment by MetaTunes** [comment]
Hi @tylla I think you have to close it. I'll work on getting the release ready. Thanks.

**Comment by tylla** [comment]
Ahh, OK, I close it now.
