### ISSUE TITLE
Plugin "Add Cluster As Release" not working

### ISSUE THREAD

**Issue by NoelDeMartin** [musicbrainz/picard-plugins#152]
I have been trying to make this plugin work with no avail, maybe I am doing something wrong but I really don't know what else to try. I installed the plugin, I even opened the python file and added my own logs, so I know it has installed correctly. But the option to "Add Cluster As Release..." is nowhere to be found. I even tried in a recently formatted computer with a clean installation and it does not work either.

The picard version I am using is 1.4.2, and I have tried with Ubuntu 16.04 and 18.04.

**Comment by phw** [comment]
Just a checklist to be sure everything is setup correctly:

1. The plugin shows up in the plugin list as installed and it is actually activated (checkbox selected)?

    ![grafik](https://user-images.githubusercontent.com/29852/41458327-93429b3a-7086-11e8-86e3-ae0eed2fdba6.png)

2. When right clicking on a cluster in the left pane is there an entry "Add Cluster As Release..." in the "Plugins" submenu?

   ![grafik](https://user-images.githubusercontent.com/29852/41458267-66203d10-7086-11e8-8433-0094ff096874.png)

**Comment by NoelDeMartin** [comment]
@phw :man_facepalming: Ok, it was not activated. It said "installed", so I was assuming it was already active. I thought the checkboxes were used to select multiple plugins in order to perform batch operations. Actually, this UI is very similar to Android SDK Manager:

![sdk_manager_packages](https://user-images.githubusercontent.com/1517677/41464777-c45bf8c8-709b-11e8-8019-c80e631fce46.png)

So well, I guess this becomes a UX bug then... Maybe you could add a name to the column with the checkboxes that says "Active", or change the status to "installed but not active" or something.

I'll leave the issue open if you want to improve the UI, but go ahead and close it if you think it's silly.

Thanks for your help!

**Comment by phw** [comment]
Agreed that the UI could be more clear here. I created https://tickets.metabrainz.org/browse/PICARD-1313 for this.

**Comment by majkinetor** [comment]
Yeah, I got the same UI problem here. And seriously, not sure why not plugins are not included already in disabled state, since all of them are less then .5MB.

Download all, enable/disable all etc would be all valuable options here.
