### ISSUE TITLE
Release Type plugin uses a method that doesn't exist in Python 3

### ISSUE THREAD

**Issue by loewenheim** [musicbrainz/picard-plugins#154]
When I activate the `Release Type` plugin in Picard 2.02, I get an error saying that `dict.iteritems()` in

https://github.com/metabrainz/picard-plugins/blob/62cd6886b6d58f5d49f24805a6207967eecb8d6c/plugins/release_type/release_type.py#L24

doesn't exist. I gather that it has been replaced by `dict.items()` in Python 3. Is this a problem with the plugin or is it a version snafu on my end?

**Comment by phw** [comment]
@loewenheim Yes, a bug. Thanks for reporting, I have submitted a fix in #156
