### ISSUE TITLE
BPM plugin not installing on Picard 2.0.4

### ISSUE THREAD

**Issue by psychoadept** [musicbrainz/picard-plugins#163]
All plugins are installing correctly for me Picard 2.0.4 except for BPM. See my report on installing plugins here: https://community.metabrainz.org/t/plugin-updates-for-picard-2-0/397185/2

**Comment by phw** [comment]
The BPM plugin does not support Windows. Please see https://tickets.metabrainz.org/browse/PICARD-1335 and related issues.
