### ISSUE TITLE
ReplayGain TypeError when calculating gain

### ISSUE THREAD

**Issue by djm2k** [musicbrainz/picard-plugins#209]
ReplayGain Logs this error upon trying to calculate for an album:

> E: 11:46:04,011 util.thread.run:56: Traceback (most recent call last):
>   File "picard\util\thread.py", line 52, in run
>   File "...\AppData\Local\MusicBrainz\Picard\plugins\replaygain.zip\replaygain\__init__.py", line 120, in _calculate_albumgain
>     calculate_replay_gain_for_files(files, format_, self.tagger)
>   File "...\AppData\Local\MusicBrainz\Picard\plugins\replaygain.zip\replaygain\__init__.py", line 43, in calculate_replay_gain_for_files
>     decode_filename(b' '.join(file_list)))
> TypeError: sequence item 0: expected a bytes-like object, str found

**Comment by harvest316** [comment]
I have this issue as well.  Even occurs when calculating for a single MP3 track.

**Comment by phw** [comment]
This was already fixed with #290 a while back.

Also there is a new replaygain2 plugin (which will be available for download in a few hours) and the old replaygain plugin is considered deprecated and will be removed in the future. See #336 for details.

.
