### ISSUE TITLE
Add support for type annotations and other python3 syntax

### ISSUE THREAD

**Issue by dseomn** [musicbrainz/picard-plugins#214]
Yes, we have an issue with the Picard website which cannot parse the plugin if it uses special Python 3 syntax. We are aware of that, but I currently can't say when we will have a fix. The quick workaround we did on the release day was to just skip plugins it could not process. Another quick way to solve it for this plugin would be to remove the type hints.

_Originally posted by @phw in https://github.com/metabrainz/picard-plugins/pull/202#issuecomment-470806751_

**Comment by phw** [comment]
See https://github.com/metabrainz/picard-website/pull/150

**Comment by phw** [comment]
Fixed
