### ISSUE TITLE
Amazon cover art 1.0 plugin won't install in Picard 2.1.3

### ISSUE THREAD

**Issue by davbe** [musicbrainz/picard-plugins#217]
When trying to install Amazon cover art : 

```
An error occured while loading the plugin 'Amazon cover art':

Plugin 'Amazon cover art' from 'C:\Users\User\AppData\Local\MusicBrainz\Picard\plugins\amazon.zip\amazon.py' is not compatible with this version of Picard.
```

Any workaround ?

Regards,

David

**Comment by phw** [comment]
You don't need to install this. This plugin specifically is only for the next Picard version 2.2, Picard 2.1.3 has the Amazon cover art provider built-in. You can enable in Options > Cover Art
