### ISSUE TITLE
Wikidata plugin continues making requests when release has been removed

### ISSUE THREAD

**Issue by psychoadept** [musicbrainz/picard-plugins#218]
I see part of the reason the wikidata genres plugin gums up the works is because it has to wait between requests. I get that. And of course the number of requests depends on the number of tracks and artists it's looking up, sure. But say I load these two releases:

https://beta.musicbrainz.org/release/e541147f-820c-465e-b577-dcf7e96bd15a
https://beta.musicbrainz.org/release/55248207-7eff-4099-a6e4-d35c5ae63166

Suddenly I've got 60+ requests. And I realize it's really the second release I want, so I remove the first one in Picard. Well, the wikidata plugin just plows ahead with ALL the requests. In fact, I can remove both releases in Picard and the plugin still goes through every wikidata request. So if I tried to load any other releases, they would go to the end of the queue and have to wait for all the previous requests to finish.

**Comment by psychoadept** [comment]
On a related note, when you switch from one version of a release to another, surely it doesn't need to make ALL the requests again? Is it possible to have it remember the ones it's already looked up, and just request ones that it doesn't have yet?

**Comment by dns53** [comment]
The plugin will cache requests and only make the request once.
If you load 2 similar releases that share recordings, artists, release groups it will use this cache.

If it is in the process of looking up something it will not look it up again but keep track of what needs to be updated once it has the information.
The counter of outstanding requests goes up but this does not make any more api calls.

**Comment by phw** [comment]
I am going to close this since the plugin can actually do nothing about that, it has neither knowledge about the album getting removed nor the ability to cancel requests.

I have added a ticket for Picard to tackle this: https://tickets.metabrainz.org/browse/PICARD-1507

**Comment by psychoadept** [comment]
Sounds good, thanks
