### ISSUE TITLE
AcousticBrainz Mood-Genre plugin should return readable data

### ISSUE THREAD

**Issue by phw** [musicbrainz/picard-plugins#228]
Currently the AcousticBrainz Mood-Genre plugin returns the data as returned from AcousticBrainz API for different models. Different models define different names for the same genre, e.g. "roc" and "rock". The plugin should return proper readable values for genres and mood.

See also discussion at https://community.metabrainz.org/t/is-there-a-reason-why-the-acousticbrainz-genres-are-in-such-a-strange-three-letter-format/439311

**Comment by alastair** [comment]
Note that you can now pass `?map_classes=true` on highlevel api queries to get nice classifier labels! https://acousticbrainz.readthedocs.io/api.html#get--api-v1-high-level

**Comment by phw** [comment]
@alastair That's very cool, thanks for the pointer. It also shows we can get the data for more than one recording with a single call, something the plugin is also not yet utilizing. I will take a look and update the plugin, this should make it much more useful.
