### ISSUE TITLE
[Feature Request]: Better convertation from Unicode to ASCII

### ISSUE THREAD

**Issue by Nero-A** [musicbrainz/picard-plugins#238]
In Picard there is the [option] (https://picard.musicbrainz.org/docs/options/) "Metadata" / "Convert Unicode punctuation characters to ASCII".
The converting is quite useful, especially if the local media player has lacks with Unicode punctuation  or mixed use of Unicode and ASCII (like Kodi).

First it's IMHO a little bit inaccurate for me because ASCII is actually a 7 bit code but the converting might be to an 8 bit code (e.g. with German umlauts). It seems to be an [extended ASCII](https://en.wikipedia.org/wiki/Extended_ASCII) but it's not clear for me, which code-page will be used, i.e. which characters will be translated. Strictly speaking the converting must depend on the used encoding (e.g.  Latin-1, Windows-1252, etc.).
It might be fine to get more details information about the converting.

The converting for Unicode to ASCII basically works fine but there are also some strange (ugly) results. E.g. [guillemets](https://en.wikipedia.org/wiki/Guillemet) ("»" and "«") will be translated to ">>" and "<<" (double greater-than or less-than sign).

It might be fine to have:

- more details documentation how the converting is done,
- more specific option for the converting (e.g. set the code-page/character set) and
- have the option to include and/or exclude characters individually (e.g. guillemet).

**Comment by Nero-A** [comment]
I know/saw the plugin [Non-ASCII Equivalents](https://github.com/metabrainz/picard-plugins/tree/2.0/plugins/non_ascii_equivalents) but it's not the solution for me.

**Comment by phw** [comment]
Please report issues regarding Picard to https://tickets.metabrainz.org/projects/PICARD/

Having said this I think the option is simply not named properly. The internal name for this is `convert_punctuation`, and that is what it actually does: It converts various forms of punctuation characters to their more generic forms as available on let's say keyboards. This is mostly for people who prefer this or need it for better compatibility (e.g. some devices might not have the fonts to display all these characters).

What this is not about is encoding, hence it does not make sense to have a encoding setting here. Encoding is a topic dealt with when saving to files, and Picard will usually work with Unicode except for ID3 where you can choose the encoding.
