### ISSUE TITLE
Fixes for "Generate M3U playlist"

### ISSUE THREAD

**Issue by SturmB** [musicbrainz/picard-plugins#245]
I have noticed two things that the plugin "Generate M3U playlist" does which I would like changed. If these should be reported as separate issues, just say so and I'll be happy to do so.

1. When launched, the "Save new playlist" directory selection dialog defaults to a directory that I no longer use. I'd like for it to default to the directory where the selected album resides, if possible. Otherwise, just default to the last chosen directory, perhaps.
2. Regardless of the chosen directory for the creation of the playlist, it **always** uses absolute pathnames to the files. This needs to be a relative directory to the chosen one for the playlist. Or, at the very least, allow the user to choose somewhere in the settings. With absolute pathnames, if the album folder is ever moved to a different location, the playlist file is useless and must be recreated. Not cool.

For now, I still have to use Tag&Rename to create playlists because it always uses relative pathnames to the MP3 files. I look forward to the day when I don't have to rely upon Tag&Rename anymore and can use Picard for all of my music management work. Even if that means I learn Python and modify the existing code to make this work the way it needs to.

**Comment by sambhavnoobcoder** [comment]
@phw kindly look into this and if any more changes are required , inform me of the same , i'll make them as well , and If it meets requirements , kindly merge the same .
