### ISSUE TITLE
ValueError Exception in Format Performer Tags

### ISSUE THREAD

**Issue by lonemadmax** [musicbrainz/picard-plugins#256]
From https://community.metabrainz.org/t/picard-plugin-format-performer-tags/402265/15
```
__init__.py, line 69, in rewrite_tag
   instruments.remove(instrument)
ValueError: list.remove(x): x not in list
```
(rest of the traceback in an image in the forum)

Four examples are given:
https://musicbrainz.org/release/6fa0ff27-1b59-3e67-9e73-213193e6e360
https://musicbrainz.org/release/357298ea-eaa2-49c8-9559-2f48019081b4
https://musicbrainz.org/release/3cca7500-d82c-4ad6-aa57-f27107a9cc72
https://musicbrainz.org/release/3f06ade0-d2ef-4cca-aae0-6254de73d96b

Keep in mind that I'm not the reporter and I haven't had that issue (yet). I just stumbled upon that thread when looking for info on some plugins, I have not even run any file through Picard yet! That and I don't know how the MB db works.

Looking at the code, I don't get what https://github.com/metabrainz/picard-plugins/blob/1d8784b9488e47102518b96392faffd062ceb058/plugins/format_performer_tags/__init__.py#L64-L69 might be trying to do. If I understand this correctly (big if) `subkey` may have something like 'background vocals and drums', that would give `instruments = ['background vocals', 'drums']` and then that is searched for guest/solo/additional items? But that last search is what https://github.com/metabrainz/picard-plugins/blob/1d8784b9488e47102518b96392faffd062ceb058/plugins/format_performer_tags/__init__.py#L72-L75 does. Even if we had 'guitar and solo guitar', we would get `instruments = ['guitar', 'solo guitar']`, with 'solo' not being an item.

One thing the four releases given have in common is at least one track with 'guest performer' and no instrument (at least as shown in web). If that is reflected as `subkey = 'guest'`, we would do something in the loop, and that something would be raise the exception: `instruments = ['guest']`, then for whatever reason https://github.com/metabrainz/picard-plugins/blob/1d8784b9488e47102518b96392faffd062ceb058/plugins/format_performer_tags/__init__.py#L68 does `instruments[0] = "guest guest"`, and the next line tries to remove the value just overwritten.

**Comment by rdswift** [comment]
@lonemadmax 

Thanks for your work in tracking down the problem.  I've added a check in the code to make sure that the instrument exists in the list before trying to remove it.  PR #257

**Comment by rdswift** [comment]
@lonemadmax 

Also, there is a bit of an explanation of how the plugin works at [https://github.com/rdswift/picard-plugins/tree/2.0/plugins/format_performer_tags](https://github.com/rdswift/picard-plugins/tree/2.0/plugins/format_performer_tags), which may help address some of your other questions.

**Comment by phw** [comment]
Fixed with https://github.com/metabrainz/picard-plugins/pull/257
