### ISSUE TITLE
Add Cluster as Release sends more tracks than needed

### ISSUE THREAD

**Issue by elnull** [musicbrainz/picard-plugins#26]
Add Cluster as Release sends more tracks than needed because self.form_values is not getting clean after previous request. Adding   self.form_values = {}  after web request solves that.

**Comment by mineo** [comment]
This is already done at https://github.com/musicbrainz/picard-plugins/blob/master/plugins/addrelease/addrelease.py#L98, can you still reproduce your problem with that version of the plugin?
