### ISSUE TITLE
AcousticBrainz Mood-Genre plugin should have a settings-page like the last-fm plugin

### ISSUE THREAD

**Issue by natrius** [musicbrainz/picard-plugins#269]
To set things like 

"Ignore genre" (alternatively split to "AcousticBrainz Mood" and "AcousticBrainz Genre",
"join multiple values with: '; / \'" or something like that. Let us choose like other plugins are doing currently
"Ignore genres" with a list separated by new line for some weird genres or moods i don't like. 

Some people just want to get moods as tags and get the genre with the last.fm plugin. Because its nice to get something like that.

**Comment by phw** [comment]
There is now a settings page in the rewritten AcousticBrainz 2.0 plugin. You can choose whether you want mood, genre or both. It even incorporates the functionality of acousticbrainz_tonal-rhythm and allows you to fetch the data from AB to more custom tags if needed.

By default it behaves as the previous version and is configured to load both mood and genre.

There are no options for joining or excluding specific genres. The idea here is that these options should be centralized in Picard itself, and that it is possible to combine multiple genre plugins.

**Comment by phw** [comment]
Closing this as the acusticbrainz plugin now provides a settings page.
