### ISSUE TITLE
Add Cluster As Release: Adds only one track of the cluster, and in wrong MBS language

### ISSUE THREAD

**Issue by jesus2099** [musicbrainz/picard-plugins#270]
I haven't used it for long time so I don't remember if there was a version change between now and my last use OK of it.

- **Picard** version **2.5.1 portable** (last time OK I did not use portable version).
- **Add Cluster As Release…** version **0.7.3**.

I have [audio ripped a concert DVD on Windows with my usual method](https://wiki.musicbrainz.org/User:Jesus2099/Concert_DVD_ripping).
This DVD unusually only contains AC3 audio (bootleg, no LPCM).
So it gave me a bunch of `.ac3` files in various folders.
I built a Picard Cluster with them and launched the plugin.

1. It opened the release editor page in French (despite my MBS being in English per setting, and Picard as well)
2. It added only the last track of the cluster in the form

Maybe it's an AC3-only issue?
I will try to convert to WAV (usually it's what I get from official concert DVD)

Here is my file list, just in case it helps:

```
VTS_01\VTS_01_CHAPTER_01_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -66ms.AC3
VTS_01\VTS_01_CHAPTER_02_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -10ms.AC3
VTS_01\VTS_01_CHAPTER_03_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -32ms.AC3
VTS_01\VTS_01_CHAPTER_04_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -5ms.AC3
VTS_01\VTS_01_CHAPTER_05_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -18ms.AC3
VTS_01\VTS_01_CHAPTER_06_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 17ms.AC3
VTS_01\VTS_01_CHAPTER_07_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -9ms.AC3
VTS_01\VTS_01_CHAPTER_08_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 0ms.AC3
VTS_01\VTS_01_CHAPTER_09_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 13ms.AC3
VTS_01\VTS_01_CHAPTER_10_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -30ms.AC3
VTS_01\VTS_01_CHAPTER_11_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -62ms.AC3
VTS_01\VTS_01_CHAPTER_12_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -6ms.AC3
VTS_01\VTS_01_CHAPTER_13_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -29ms.AC3
VTS_01\VTS_01_CHAPTER_14_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 27ms.AC3
VTS_01\VTS_01_CHAPTER_15_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 21ms.AC3
VTS_01\VTS_01_CHAPTER_16_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 19ms.AC3
VTS_01\VTS_01_CHAPTER_17_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 35ms.AC3
VTS_01\VTS_01_CHAPTER_18_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -15ms.AC3
VTS_01\VTS_01_CHAPTER_19_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -54ms.AC3
VTS_01\VTS_01_CHAPTER_20_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY 44ms.AC3
VTS_05\VTS_05_CHAPTER_01_1 - 0x80 - Audio - AC3 - 2ch - 48kHz - DRC - Deutsch - DELAY -66ms.AC3
```

Maybe I should do a separate ticket for the language issue… 🤔

**Comment by jesus2099** [comment]
OK after I have tagged the `.ac3` files in foobar2000 it didn't change.

But once I added **track numbers**, it finally submitted all tracks of the cluster!
So **track numbers are mandatory**.

Still my MBS release editor (`/release/add`) is opened in French. Although if I manually go to a blank `/release/add` page, it's in English, as my MBS settings say.

**Comment by Freso** [comment]
Seems like the language issue got sorted. :)

If you can still replicate the track clustering issue, could you perhaps attach the HTML file the plugin generates? I’m guessing Picard and/or the plugin are failing to parse track numbers, which means that all the tracks are being sent to the editor seeder with the same number, causing MBS to disregard all but one of them.

**Comment by phw** [comment]
FYI: The upcoming Picard 2.7 will have this cluster submission feature integrated (originally to fix PICARD-2202, see PICARD-2203), and I think it will fix the issue with the track numbers. The plugin will then get deprecated.

**Comment by jesus2099** [comment]
@Freso> I’m guessing Picard and/or the plugin are failing to parse track numbers

My files had no track numbers.
I had to add track numbers using an Mp3tag macro (Ctrl+K or something?) before I could submit my tracks.
I think in the past it didn't require track numbers to properly add cluster as release… 🤔

**Comment by phw** [comment]
This should work as expected with the built-in functionality in current Picard.

**Comment by jesus2099** [comment]
Thanks, I installed 2.7.3.
I will see next time. :)
