### ISSUE TITLE
ReplayGain plugin not compatible with latest version

### ISSUE THREAD

**Issue by acastaner** [musicbrainz/picard-plugins#28]
I'm running Picard 1.3.2 on Windows (10) and when I try to load the ReplayGain plugin I get an error message that "the plugin 'ui_options-replaygain' is not compatible with this version of Picard." This happens when I load the `ui_options_replaygain.py` file directly. If I load the `__init__.py` file then just nothing happens.

**Comment by mineo** [comment]
You need to put all the files of the plugin into a subdirectory of the plugin directory, so it looks like
```
plugins/replaygain
├── __init__.py
├── options_replaygain.ui
└── ui_options_replaygain.py
```

(replaygain is the subdirectory of the plugin directory in this case). We should probably improve the zip files to include that directory.

**Comment by MichaelTiebesl** [comment]
I have the same problem. I use Linux (Ubuntu 15.04) Picard 1.3.2
It didn't work for me also with the subdirectory.

**Comment by mineo** [comment]
I'm not sure if those are the same problems, but can you open a terminal, start Picard in debug mode (`picard -d`) from there and paste the output? Also, do you have the plugin enabled in the options (yes, sometimes people forget that)?

**Comment by MichaelTiebesl** [comment]
Hi there mineo,
I see already some errors in the output about the plugins what are not working.
http://pastebin.ubuntu.com/12319428/
Plugins are enabled in the options to inform you.

**Comment by mineo** [comment]
Are you sure the plugin is not working? It gets loaded correctly (`Loading plugin u'ReplayGain' version 0.1, compatible with API: 0.15, 0.16`). Being able to activate it in the options also means that the plugin was loaded successfully.

**Comment by zas** [comment]
`W: 16:08:18 Plugin 'ui_options_replaygain' from '/home/michael/.config/MusicBrainz/Picard/plugins/ui_options_replaygain.py' is not compatible with this version of Picard.` looks weird.
Be sure you don't have replaygain files at plugins directory level AND plugins/replaygain level.

**Comment by MichaelTiebesl** [comment]
In the menu and options plugin i can see that the plugin is installed, i only don't get the option menu for the ReplayGain plugin. That is the one what is not installed. See the first post here from @acastaner.

![plugin menu](https://cloud.githubusercontent.com/assets/10792019/9757782/3995d670-5715-11e5-9a77-475fd3c6c741.png)

After using the plugin ReplayGain i can see it is working.
![value](https://cloud.githubusercontent.com/assets/10792019/9757819/6e8edf20-5715-11e5-8b53-b5760929fa7d.png)

I only don't have the options replaygain installed.

In the output i can see a few errors:
* Plugin directory '/usr/lib/picard/contrib/plugins' doesn't exist
* Module 'replaygain' conflict: unregistering previously loaded u'ReplayGain' version 0.1 from '/usr/lib/picard/picard/plugins/replaygain'
* Plugin 'ui_options_replaygain' from      '/home/michael/.config/MusicBrainz/Picard/plugins/ui_options_replaygain.py' is not compatible with this  version of Picard.

**Comment by zas** [comment]
> Plugin directory '/usr/lib/picard/contrib/plugins' doesn't exist

Just a warning, Picard tries to load plugins from this directory, but it can't.

> Module 'replaygain' conflict: unregistering previously loaded u'ReplayGain' version 0.1 from '/usr/lib/picard/picard/plugins/replaygain'

Your locally installed plugin takes over the system wide installed plugin, just a warning.

> Plugin 'ui_options_replaygain' from '/home/michael/.config/MusicBrainz/Picard/plugins/ui_options_replaygain.py' is not compatible with this version of Picard. 

Rremove `/home/michael/.config/MusicBrainz/Picard/plugins/ui_options_*`, those are leftover from a previous buggy installation, and shouldn't be there (Picard tries to load them as plugins, but they aren't, they belongs to subdirs replaygain and lastfmplus).

**Comment by MichaelTiebesl** [comment]
I'm lost with this i can see. I re-installed everything again here on Linux. Installed by ppa. Also follow all suggested advice but it is the same at the end.

**Comment by zas** [comment]
> I'm lost with this i can see. I re-installed everything again here on Linux. Installed by ppa. Also follow all suggested advice but it is the same at the end.

Can you repost your debug log after this re-installation ?

**Comment by MichaelTiebesl** [comment]
http://pastebin.ubuntu.com/12327198/

**Comment by zas** [comment]
@MichaelTiebesl : the debug log looks clean to me, what do you mean by "it is the same at the end" ?
After plugin installation you should have plugin options  added to Options > Plugins as a subpage.

**Comment by MichaelTiebesl** [comment]
Hi there zas, what i mean is that at the end, after re-install everything it is the same as how i started. 
When I try to load the ReplayGain plugin I get an error message that "the plugin 'ui_options-replaygain' is not compatible with this version of Picard." This happens when I load the ui_options_replaygain.py file directly. If I load the __init__.py file then just nothing happens.

**Comment by MichaelTiebesl** [comment]
![error](https://cloud.githubusercontent.com/assets/10792019/9802729/2ee097b6-584f-11e5-8c42-ff110520fc4d.png)

![plugin](https://cloud.githubusercontent.com/assets/10792019/9802745/3b8d2c86-584f-11e5-8b47-ebb6b8e3d7ff.png)

![replay](https://cloud.githubusercontent.com/assets/10792019/9802748/401665f6-584f-11e5-9445-57712a66bf4f.png)

**Comment by zas** [comment]
@MichaelTiebesl : "This happens when I load the ui_options_replaygain.py file directly. If I load the init.py file then just nothing happens." ?? I don't get what you are doing there.

You should have the following files in your `.config/MusicBrainz/Picard/plugins` : 
* `replaygain`
 * `__init__.py`
 * `options_replaygain.ui`
 * `ui_options_replaygain.py`

You shouldn't have any `ui_options_replaygain.py` elsewhere, and it shouldn't be loaded as a plugin (it is used by `replaygain/__init__.py` but it isn't a plugin by itself).

Now, i don't see the warning you have in the screenshot in the debug.log you provided, i guess those are from different runs.

**Comment by MichaelTiebesl** [comment]
These are the latest screenhots and last debug log. 

![picard](https://cloud.githubusercontent.com/assets/10792019/9844723/4d1ea564-5af8-11e5-8508-11d58228c209.png)

http://pastebin.ubuntu.com/12406848/

I uploaded an album to see what heappens in debug log.

**Comment by phw** [comment]
@MichaelTiebesl Ok, that looks good now. What problem do you still have?

**Comment by MichaelTiebesl** [comment]
plugins lastfmPlus and replaygain are not working
i don't see the options menu with the replaygain and lastfmplus is totally not working at this moment

**Comment by zas** [comment]
@MichaelTiebesl : please upload the full debug log (picard -d)

**Comment by MichaelTiebesl** [comment]
Sorry my mistake: http://pastebin.ubuntu.com/12407006/

**Comment by phw** [comment]
> i don't see the options menu with the replaygain and lastfmplus is totally not working at this moment

I am confused here. In the screens you posted earlier the Plugins > ReplayGain menu in the options is clearly visible.

Have you tried removing the plugin from `.config/MusicBrainz/Picard/plugins` completely? According to your log Picard also finds the plugin in the global plugin directory /usr/lib/picard/picard/plugins/`, maybe this is causing the problem (even though it shouldn't).

**Comment by MichaelTiebesl** [comment]
Lol, now i also got confused by your reply. I thought with the option in Replaygain that i should get a tab or something where i can do some settings for the Replaygain. I only have in plugin 1 page with no tabs. On that page there is only visible the location from vorbisgain and mp3gain. See picture above. You are correct that in the plugin "directory ui_options_replaygain.py" is installed.

**Comment by phw** [comment]
Yep, that's pretty much it. No further options. For usage you select a track or album on the right pane in Picard and select `Plugins -> Calculate Album Gain...` (or track gain) from the right-click menu. The plugin will call the command line tool on the files selected (you need to have those tools installed separately). No further feedback, just some short message in the Picard status bar if I remember correctly.

The plugin is *very* crude. As the original author I had always hoped somebody would improve it, but it worked for me back when I wrote it.

**Comment by phw** [comment]
Regarding lastfmplus there is a discussion on http://forums.musicbrainz.org/viewtopic.php?id=5903 . I personally don't know what the status is, though.

**Comment by MichaelTiebesl** [comment]
@phw  and @zas, I think i found the issue. It is just there is no option menu at all in replaygain plugin. 
I always thought from the beginning that there should be an option menu. "options_replaygain.ui" and 
"ui_options_replaygain.py" make me think that. So after the explonation from @phw it makes me everything clear. Also the link to the discussion about lastfmplus is clear to me now.

Thanks for the time so far. ;)
