### ISSUE TITLE
[acousticbrainz_tonal-rhythm] Rate limit issues

### ISSUE THREAD

**Issue by Sophist-UK** [musicbrainz/picard-plugins#282]
When loading albums I have been receiving error messages in the log like:
```
E: 23:37:19,087 webservice\__init__._handle_reply:445: Network request error for http://acousticbrainz.org:80/api/v1/high-level?recording_ids=f2ada1c9-fa39-4d15-aa11-9bd798a885a9&map_classes=true: Error transferring http://acousticbrainz.org:80/api/v1/high-level?recording_ids=f2ada1c9-fa39-4d15-aa11-9bd798a885a9&map_classes=true - server replied: TOO MANY REQUESTS (QT code 299, HTTP code 429)
E: 23:37:19,134 webservice\__init__._handle_reply:445: Network request error for http://acousticbrainz.org:80/f2ada1c9-fa39-4d15-aa11-9bd798a885a9/low-level: Error transferring http://acousticbrainz.org:80/f2ada1c9-fa39-4d15-aa11-9bd798a885a9/low-level - server replied: TOO MANY REQUESTS (QT code 299, HTTP code 429)
```
Looking at the code for this plugin, the rate limit appears to be hard coded whereas the [AcousticBrainz API manual](https://acousticbrainz.readthedocs.io/api.html#rate-limiting) seems to suggest that rate limiting is variable and is reported in the response headers.

IMO this plugin needs to be enhanced to process these response headers and feed them back to the webservice rate limiting functionality. In the mean time I will put forward a small PR which will increase the rate limit from 50ms to 100ms in order to try to avoid these sorts of errors (at the cost of slower lookups).

**Comment by phw** [comment]
The updated acousticbrainz plugin will replace the tonal rhythm plugin, as it integrates the functionality of it. It also somewhat mitigates the rate limiting issue as it is doing less requests overall (it batches requests for mulltiple recordings of one release, so ideally it ends up with one request per release).

It is no full support for the dynamic rate limiting of the AB server, though. Proper support for this would best be added to Picard's web service module, though. See PICARD-1681

**Comment by phw** [comment]
Closing this as this now is working well by the acousticbrainz plugin, which does less requests per album.
