### ISSUE TITLE
Album Artist Website cannot handle multiple websites

### ISSUE THREAD

**Issue by aw-was-here** [musicbrainz/picard-plugins#287]
Artists like [Daft Punk](https://musicbrainz.org/artist/056e4f3e-d505-4dad-8ec1-d04f521cbb56) have two websites listed.  Using the 'Album Artist Website' plug-in, the tag that gets generated is a concatenation of both.  For this example, 'http://mouskni.com/artists/daft-punk//http://www.daftpunk.com/'.

**Comment by Sophist-UK** [comment]
Actually the tag that is loaded by this plugin is (depending on when / how you view it) either: `['http://mouskni.com/artists/daft-punk/', 'http://www.daftpunk.com/']` or `http://mouskni.com/artists/daft-punk/; http://www.daftpunk.com/`.

It then gets saved in the particular tagging structure of the file format you are using, and then displayed by the music player.

So you will need to give more information about the file types of your music, perhaps about the Picard settings you are using and the music player.

**Comment by aw-was-here** [comment]
I'll just close this for now. Thanks.
