### ISSUE TITLE
Plugin to copy tags between tracks

### ISSUE THREAD

**Issue by abbluiz** [musicbrainz/picard-plugins#313]
I was searching for a plugin or native functionality that enables me to copy tags and its information from a track and imports it into another. Example: I select a track and its tags and press CTRL+C, select another track and then CTRL+V to import the tags into it.

It seems simple enough, but I could not find it. Anybody knows about anything similar?

**Comment by phw** [comment]
This actually should be implemented for Picard itself, a plugin cannot properly access what happens on keystroked on the metadata view (without using some dirty hacks).

As for know you can only copy values, but not entire tags.

**Comment by phw** [comment]
I added ticket PICARD-2287 for this

**Comment by abbluiz** [comment]
@phw Thanks for the answer and for adding the ticket! Yes, for now I will be manually copying the value itself, but I think it would be a nice add to implement it that way.

**Comment by daryltucker** [comment]
This would be incredible.  Thank you.
