### ISSUE TITLE
Cannot install Classical Music Extras 

### ISSUE THREAD

**Issue by sjkiss** [musicbrainz/picard-plugins#316]
Hi there:
I'm so pumped about the Classical Extras plugin, but the documentation is super unhelpful about how to install it. It simply reads: 

> Installation
> Install the zip file in your plugins folder in the usual fashion

OK.....So I've gone into the Plugins menu in MusicBrainz Picard and tried to download and install there> 

<img width="1601" alt="Screen Shot 2021-10-12 at 11 55 18 AM" src="https://user-images.githubusercontent.com/5245117/136989521-2b6185bb-5662-4c98-8e6d-4cfa5061f806.png">

And I've also gone into the file folder and unzipped the package. 

<img width="1222" alt="Screen Shot 2021-10-12 at 11 55 52 AM" src="https://user-images.githubusercontent.com/5245117/136989614-21410fe3-d11b-46ba-87c4-27528632dc05.png">

And there seems to be nothing added to the MusicBrainz Option menu. 

<img width="148" alt="Screen Shot 2021-10-12 at 11 56 30 AM" src="https://user-images.githubusercontent.com/5245117/136989724-eb0a64e5-67c2-420d-8ada-e91611d422fa.png">

So, how do I install the damn thing!! Thank you!

**Comment by MetaTunes** [comment]
Which version of Picard are you using and on what OS?

**Comment by MetaTunes** [comment]
And have you tried just clicking the red x, to remove the disabled status?

**Comment by MetaTunes** [comment]
@sjkiss : Is this still open?

**Comment by sjkiss** [comment]
No, I got this sorted. Thank you!

**Comment by MetaTunes** [comment]
Could you close it then please @sjkiss
