### ISSUE TITLE
Work 

### ISSUE THREAD

**Issue by ChrisMail2014** [musicbrainz/picard-plugins#321]
Please report issues to the most appropriate project and component at
https://tickets.metabrainz.org

For informal discussions, simply join MetaBrainz community forums at
https://community.metabrainz.org

For instant chat about development, join #metabrainz IRC channel at
ircs://irc.libera.chat:6697/metabrainz

**Comment by phw** [comment]
Anything specific you wanted to say with this issue? Or is it some copy and paste going wrong?
