### ISSUE TITLE
Add Cluster As Release uses hardcoded musicbrainz URI instead of "Server address" option

### ISSUE THREAD

**Issue by LeoVerto** [musicbrainz/picard-plugins#33]
Since Picard has a setting to set a custom server address and port (for example to use the beta site), Add Cluster As Release should probably use that instead of relying on a hardcoded value.

**Comment by zas** [comment]
I provided an untested patch, check if it works for you.

**Comment by LeoVerto** [comment]
Confirmed working, thanks for the quick patch. :+1:

**Comment by TrueOsiris** [comment]
The opposite of this should be true.
You can and should only add releases to musicbrainz.org, not to another mirror.

**Comment by LeoVerto** [comment]
@TrueOsiris Why would you want to artificially limit user choice with that assumption?

My reason for opening this issue was simply that I wanted to use Picard with beta.musicbrainz.org, which as it turns out, is another perfectly legit place to add releases and I'm sure there are other use cases, where having the option to set the server would be useful!
