### ISSUE TITLE
[Add Cluster as Release] Plug-in adds extra tracks to album

### ISSUE THREAD

**Issue by CyberSkull** [musicbrainz/picard-plugins#4]
I cam across an odd bug in `Add Cluster as Release` today. I added an [18 track album](http://musicbrainz.org/release/60700efa-113a-4a6c-9160-6360a6d70a56), then later added a [15 track album](http://musicbrainz.org/release/d9287622-67dd-4277-a51c-ce2909fac4a7), but it tacked on the last 3 tracks from the prior album in the submission. I've tried submitting again through the plug-in and can confirm something is keeping the prior submitted tracks cached.

* OS: Mac OS X 10.10
* Picard: 1.3
* Add Cluster as Release: 0.5

**Comment by mineo** [comment]
@CyberSkull can you still reproduce this? I've fixed this in https://github.com/musicbrainz/picard/commit/50bc0755af0e4bb47b45120daa7126375f6e0bc3 (without updating the version number :/), so I'm unsure whether you were just using an old 0.5 version of the plugin or if the fix was not correct.

**Comment by CyberSkull** [comment]
I downloaded and installed the version of the plugin you linked to, and it does not fix the issue. I added an album that has 6 volumes, then added an album with 1 volume, and the additional tracks were still appended to the second album.

* OS: Mac OS X 10.10.1
* Picard 1.3.2
* Add Cluster as Release 0.5 (50bc075)

**Comment by mineo** [comment]
You actually need the plugin from at least the commit after that one because I forgot the parantheses around the method call which cleared the internal state that's responsible for this bug. You can simply take the plugin from current master (https://raw.githubusercontent.com/musicbrainz/picard/master/contrib/plugins/addrelease.py) which has them. Sorry for not being clear about that in the previous comment.

**Comment by zas** [comment]
> using an old 0.5 version of the plugin or if the fix was not correct.

Wasn't the version updated after changes ?

**Comment by CyberSkull** [comment]
Seems to be fixed in the master branch (though you should update the version number 😉).

**Comment by mineo** [comment]
I've now incremented the version number in picards repository. What is the proper way to get this change into this repository? Manually applying that change, or is there a script that I can run that automatically gets the latest changes from picards repo?

**Comment by phw** [comment]
You have to copy the plugin to the picard-plugins repository manually.

I think the proper fix would be to finally do a `git rm -r contrib/plugins/` and use only picard-plugins. For convenience we could add the plugins repository as a git submodule, if people want this.

**Comment by mineo** [comment]
I've now opened #11 to update the plugin included here.

+1 to @phw s suggestion.

**Comment by zas** [comment]
> I think the proper fix would be to finally do a git rm -r contrib/plugins/ and use only picard-plugins. For convenience we could add the plugins repository as a git submodule, if people want this.

I agree too.
